import { prisma } from "@gymorbit/db";
import { requireStaff } from "../../lib/guards";
import { createMember } from "./actions";
import QRCode from "qrcode";

export default async function MembersPage({ searchParams }: { searchParams?: { q?: string } }) {
  await requireStaff(); const q = searchParams?.q?.trim() ?? "";
  const [members, plans] = await Promise.all([prisma.member.findMany({ where: q ? { OR: [{ name: { contains: q, mode: "insensitive" } }, { phone: { contains: q } }, { memberCode: { contains: q, mode: "insensitive" } }] } : undefined, include: { subscriptions: { include: { plan: true }, orderBy: { endDate: "desc" }, take: 1 } }, orderBy: { joinedAt: "desc" }, take: 50 }), prisma.plan.findMany({ where: { isActive: true }, orderBy: { price: "asc" } })]);
  const rows = await Promise.all(members.map(async (member) => ({ member, qr: await QRCode.toDataURL(member.memberCode, { margin: 0, width: 56 }) })));
  return <main className="main"><div className="eyebrow">Member management</div><h1>Members</h1><div className="toolbar"><form><input className="search" name="q" defaultValue={q} placeholder="Search name, phone or code" /><button className="secondary">Search</button></form><a className="button secondary" href="/api/members/export">Export CSV</a></div><section className="card"><h2>Add member</h2><form action={createMember} className="form-grid"><label>Name<input name="name" required /></label><label>Phone<input name="phone" required /></label><label>Email<input name="email" type="email" /></label><label>Plan<select name="planId" required defaultValue=""><option value="" disabled>Select a plan</option>{plans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} — Rs {(plan.price / 100).toLocaleString()}</option>)}</select></label><button className="full" type="submit">Create member & assign plan</button></form></section><section className="card" style={{ marginTop: 18 }}><table className="table"><thead><tr><th>Member</th><th>Code / QR</th><th>Plan</th><th>Expiry</th><th>Status</th></tr></thead><tbody>{rows.map(({ member, qr }) => { const sub = member.subscriptions[0]; return <tr key={member.id}><td><strong>{member.name}</strong><br /><span className="muted">{member.phone}</span></td><td>{member.memberCode}<br /><img src={qr} alt={`QR for ${member.memberCode}`} width="38" height="38" /></td><td>{sub?.plan.name ?? "—"}</td><td>{sub?.endDate.toLocaleDateString() ?? "—"}</td><td><span className="badge">{member.status}</span></td></tr>; })}</tbody></table></section></main>;
}
